spring:
   application:
      name: training

   datasource:
      # hikari: schema: development
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/formation_db
      username: trainer
      password: trainer
      hikari:
         auto-commit: true
         maximum-pool-size: 1024

   jpa:
      show-sql: true
      open-in-view: true
      generate-ddl: true
      properties:
         hibernate:
            format_sql: true
            globally_quoted_identifiers: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         # create, update, create-drop, validate and none
         ddl-auto: update
         naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
            #physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   batch:
      jdbc:
         isolation-level-for-create: default

app:
   properties:
      version: 1.0
      name: My project
